### ISSUE TITLE
CUDA/torch error since updating to 0.7.0

### ISSUE THREAD

**Issue by rdrighetto** [MPI-Dortmund/tomotwin-cryoet#74]
Hey TomoTwins!

@cmccaffe and I have been stumbling upon a strange error (see full error message below) when trying to embed a tomo:

`tomotwin_embed.py tomogram -m /scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_model_p120_052022_loss.pth -v /scicore/home/engel0006/GROUP/pool-visprot/Caitie/TomoTwin/Tkiv/tomo9/9.rec -b 256 -o /scicore/home/engel0006/GROUP/pool-visprot/Caitie/TomoTwin/Tkiv/tomo9/embed/tomo/ -s 2`

This has been happening since updating to v0.7.0. We believe this might be due to some recent update in pytorch, because that has broken membrain-seg too. The error messages seem cryptic, but according to this thread it could be a problem with the loss function:
https://stackoverflow.com/questions/68277801/extracting-meaningful-error-message-from-runtimeerror-cuda-error-device-side
I'm mentioning this because in membrain-seg we got error messages that mentioned the loss function explicitly, but I'm not sure if it's related. Pinging @LorenzLamm here because he managed to fix membrain-seg so maybe he has some advice.

Any ideas?

Thanks a lot!

```
Latest version of TomoTwin is installed :-)
Found 1 GPU(s). Start DDP + Compiling.
reading /scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_model_p120_052022_loss.pth
Model config:
{'identifier': 'SiameseNet', 'network_config': {'output_channels': 32, 'dropout': 0.2, 'repeat_layers': 0, 'norm_name': 'GroupNorm', 'norm_kwargs': {'num_groups': 64, 'num_channels': 1024}, 'gem_pooling_p': 0}, 'train_config': {'loss': 'TripletLoss', 'tl_margin': 0.539, 'miner': True, 'miner_margin': 0.734, 'learning_rate': 5.945e-05, 'optimizer': 'Adam', 'weight_decay': 0, 'batchsize': 35, 'patience': 50, 'aug_train_shift_distance': 2}, 'distance': 'COSINE', 'window_size': (37, 37, 37)}
Traceback (most recent call last):                                                                                                                                        
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/bin/tomotwin_embed.py", line 8, in <module>
    sys.exit(_main_())
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/tomotwin/embed_main.py", line 630, in _main_
    start(config)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/tomotwin/embed_main.py", line 618, in start
    run_distr(config, world_size)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/tomotwin/embed_main.py", line 604, in run_distr
    mp.spawn(
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1084, in _record
    static_outputs = model(inputs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 401, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/scratch/torchinductor_diogori/ou/cou7qwba4awtz6sdrugswxxjpfrrzyvzysk4ckcmf6ftq3a52drp.py", line 481, in call
    buf2 = extern_kernels.convolution(buf0, buf1, stride=(1, 1, 1), padding=(0, 0, 0), dilation=(1, 1, 1), transposed=False, output_padding=(0, 0, 0), groups=1, bias=None)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/tomotwin/embed_main.py", line 584, in run
    embed_tomogram(tomo, embedor, conf, window_size, mask)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/tomotwin/embed_main.py", line 512, in embed_tomogram
    embeddings = sliding_window_embedding(tomo=tomo, boxer=boxer, embedor=embedor)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/tomotwin/embed_main.py", line 409, in sliding_window_embedding
    embeddings = embedor.embed(volume_data=boxes)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/tomotwin/modules/inference/embedor.py", line 600, in embed
    subvolume = self.model.forward(subvolume).type(torch.HalfTensor)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/tomotwin/modules/networks/SiameseNet3D.py", line 522, in forward
    def forward(self, inputtensor):
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/fx/graph_module.py", line 678, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/fx/graph_module.py", line 284, in __call__
    raise e
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/fx/graph_module.py", line 274, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.214", line 6, in forward
    submod_0 = self.compiled_submod_0(l_inputtensor_);  l_inputtensor_ = None
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_dynamo/backends/distributed.py", line 335, in forward
    x = self.submod(*args)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 3905, in forward
    return compiled_fn(full_args)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1482, in g
    return f(*args)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2533, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1506, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1594, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 374, in __call__
    return self.get_current_callable()(inputs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 680, in run
    return compiled_fn(new_inputs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 368, in deferred_cudagraphify
    return fn(inputs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 628, in run
    return model(new_inputs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1741, in run
    out = self._run(new_inputs, function_id)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1815, in _run
    return self.record_function(new_inputs, function_id)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1846, in record_function
    node = CUDAGraphNode(
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 892, in __init__
    ] = self._record(wrapped_function.model, recording_inputs)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/_inductor/cudagraph_trees.py", line 1076, in _record
    with preserve_rng_state(), torch.cuda.device(
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/cuda/graphs.py", line 197, in __exit__
    self.cuda_graph.capture_end()
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/tomotwin/tomotwin_env/lib/python3.10/site-packages/torch/cuda/graphs.py", line 88, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


```

**Comment by thorstenwagner** [comment]
Hi,

thanks for the report and the loveley nickname :-D 

I'm not sure what the problem is, but I don't think that it is the loss function because it isn't called during embedding. Additionally, I'm running the current version on several machines since a while.


To further pin down the problem:

1. Does that also happen when you run tomotwin on multiple GPUs?

2. Could run the embed command with -d 0? It will be slower but does not use some of the advanced pytorch features, which might be problem on your side.

Best
Thorsten



08.11.2023 14:45:41 Ricardo Righetto ***@***.***>:

**Comment by rdrighetto** [comment]
Hi @thorstenwagner, thanks for getting back so quickly!

Quick update:

1. Yes, the same error occurs when we run tomotwin on multiple GPUs (using `CUDA_VISIBLE_DEVICES=0,1`)

2. Adding `-d 0` to the command line above does seem to work (as in: it's currently calculating the embeddings and the progress bar is moving, which didn't happen before)

Hope this is useful somehow, let us know if there are other things we can try!

**Comment by thorstenwagner** [comment]
Ok, interesting. You probably used the update instructions from the documentaiton? Now I got some feedback by other users, that they had to make fresh environment for TomoTwin 0.7. Could you maybe also try this?

If it still crashes, I would like to see the output of `pip freeze`.

Thank you for your help debugging this!

**Comment by rdrighetto** [comment]
Hi Thorsten,

Yes, first I tried updating using your instructions. When that failed I did a fresh install of v0.7.0 from scratch, and got the same error.

FYI: we are still running CentOS 7.9 on our cluster which is quite old by now. Package updates are increasingly less compatible with that...
Anyway, here is the output of `pip freeze`:

```
absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1695154477682/work
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1696765415812/work
aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1667935791922/work
alembic @ file:///home/conda/feedstock_root/build_artifacts/alembic_1698347477885/work
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1693488585952/work
async-timeout @ file:///home/conda/feedstock_root/build_artifacts/async-timeout_1691763562544/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1683424013410/work
blinker @ file:///home/conda/feedstock_root/build_artifacts/blinker_1698890160476/work
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1660586590972/work
Brotli @ file:///home/conda/feedstock_root/build_artifacts/brotli-split_1687884021435/work
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1698197297464/work
certifi==2023.7.22
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1696001684923/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1698833585322/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1692311806742/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1697464713350/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
colorlog==6.7.0
contourpy @ file:///home/conda/feedstock_root/build_artifacts/contourpy_1699041363598/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography-split_1698192013143/work
cubinlinker @ file:///home/conda/feedstock_root/build_artifacts/cubinlinker_1684752888972/work
cuda-python @ file:///opt/conda/conda-bld/cuda-python_1697577638473/work
cudf==23.4.1
cuml==23.4.1
cupy @ file:///home/conda/feedstock_root/build_artifacts/cupy_1677786697638/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1696677705766/work
cytoolz @ file:///home/conda/feedstock_root/build_artifacts/cytoolz_1695545144718/work
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1679692358967/work
dask-cuda @ file:///opt/conda/conda-bld/work
dask-cudf==23.4.1
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1680715567006/work
dnspython @ file:///home/conda/feedstock_root/build_artifacts/dnspython_1697529688148/work
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1692026125334/work
fastavro @ file:///home/conda/feedstock_root/build_artifacts/fastavro_1698469173730/work
fastrlock @ file:///home/conda/feedstock_root/build_artifacts/fastrlock_1695477316330/work
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1698714947081/work
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1699023517309/work
frozenlist @ file:///home/conda/feedstock_root/build_artifacts/frozenlist_1695377693328/work
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1697919321618/work
gmpy2 @ file:///home/conda/feedstock_root/build_artifacts/gmpy2_1666808654411/work
google-auth @ file:///home/conda/feedstock_root/build_artifacts/google-auth_1698826879221/work
google-auth-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/google-auth-oauthlib_1694470453154/work
greenlet @ file:///home/conda/feedstock_root/build_artifacts/greenlet_1698243357024/work
grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpc-split_1690942284331/work
h11 @ file:///home/conda/feedstock_root/build_artifacts/h11_1664132893548/work
h2 @ file:///home/conda/feedstock_root/build_artifacts/h2_1634280454336/work
hpack==4.0.0
httpcore @ file:///home/conda/feedstock_root/build_artifacts/httpcore_1699030646176/work
hyperframe @ file:///home/conda/feedstock_root/build_artifacts/hyperframe_1619110129307/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
imageio==2.32.0
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1688754491823/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1699364556997/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1691577114857/work
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1695379902431/work
lazy_loader==0.3
llvmlite==0.39.1
locket @ file:///home/conda/feedstock_root/build_artifacts/locket_1650660393415/work
lz4 @ file:///home/conda/feedstock_root/build_artifacts/lz4_1695448705999/work
Mako @ file:///home/conda/feedstock_root/build_artifacts/mako_1668568582731/work
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1698797478597/work
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1695367434228/work
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1698868520350/work
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1678228039184/work
mrcfile==1.4.3
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1695464100672/work
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1696716075096/work
munkres==1.1.4
mysql-connector-python==8.0.31
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1698504735452/work
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1680825379968/work
numexpr @ file:///home/conda/feedstock_root/build_artifacts/numexpr_1697637021179/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1668919096861/work
nvtx @ file:///home/conda/feedstock_root/build_artifacts/nvtx_1695897163239/work
oauthlib @ file:///home/conda/feedstock_root/build_artifacts/oauthlib_1666056362788/work
optuna @ file:///home/conda/feedstock_root/build_artifacts/optuna_1697796397859/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1696202382185/work
pandas==1.5.3
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1695667515973/work
patsy @ file:///home/conda/feedstock_root/build_artifacts/patsy_1665356157073/work
Pillow==10.0.1
ply==3.11
protobuf==4.21.12
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1695367094274/work
ptxcompiler @ file:///home/conda/feedstock_root/build_artifacts/ptxcompiler_1697578517938/work
py-cpuinfo @ file:///home/conda/feedstock_root/build_artifacts/py-cpuinfo_1666774466606/work
pyarrow==10.0.1
pyasn1 @ file:///home/conda/feedstock_root/build_artifacts/pyasn1_1694615621498/work
pyasn1-modules @ file:///home/conda/feedstock_root/build_artifacts/pyasn1-modules_1695107857548/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1689721553971/work
pylibraft==23.4.1
pynvml @ file:///home/conda/feedstock_root/build_artifacts/pynvml_1639061605391/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1698795453264/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1690737849915/work
PyQt5==5.15.9
PyQt5-sip==12.12.2
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
pyStarDB==0.4.2
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytorch-metric-learning==1.6.3
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1693930252784/work
pyu2f @ file:///home/conda/feedstock_root/build_artifacts/pyu2f_1604248910016/work
PyYAML @ file:///home/conda/feedstock_root/build_artifacts/pyyaml_1695373428874/work
raft-dask==23.4.1
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
requests-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/requests-oauthlib_1643557462909/work
rmm==23.4.1
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1658328885051/work
scikit-image==0.22.0
scikit-learn==1.3.2
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy-split_1696467628975/work/dist/scipy-1.11.3-cp310-cp310-linux_x86_64.whl#sha256=1a1f6f0b1d49eca3673dad934971d667767456b5f7effcaf9f07cdd3ba377c95
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1696262444380/work
setuptools-scm==8.0.4
sip @ file:///home/conda/feedstock_root/build_artifacts/sip_1697300428978/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
SQLAlchemy @ file:///home/conda/feedstock_root/build_artifacts/sqlalchemy_1698950567251/work
statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1696548122882/work
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1684180540116/work
tables @ file:///home/conda/feedstock_root/build_artifacts/pytables_1696670791550/work
tabulate==0.9.0
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1694702375735/work
tensorboard @ file:///home/conda/feedstock_root/build_artifacts/tensorboard_1699025239851/work/tensorboard-2.15.1-py3-none-any.whl#sha256=c46c1d1cf13a458c429868a78b2531d8ff5f682058d69ec0840b0bc7a38f1c0f
tensorboard-data-server @ file:///home/conda/feedstock_root/build_artifacts/tensorboard-data-server_1695425366946/work/tensorboard_data_server-0.7.0-py3-none-manylinux2014_x86_64.whl#sha256=aa1f69b2111bb4309cc6277ac277c89a9f67d074aa666b96eebe7401a359e1d5
threadpoolctl==3.2.0
tifffile==2023.9.26
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
tomotwin-cryoet==0.7.0
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
torch==2.1.0
torchvision==0.16.0
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1695373560918/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1691671248568/work
treelite==3.2.0
treelite-runtime==3.2.0
triton==2.1.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1695040754690/work
ucx-py @ file:///opt/conda/conda-bld/work
unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1695847980273/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1697720414277/work
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1698235201373/work
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1696732509758/work
zict @ file:///home/conda/feedstock_root/build_artifacts/zict_1681770155528/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1695255097490/work
```

**Comment by thorstenwagner** [comment]
Hm, I don't see important differences. However, some packages are not listed. The error is related to cudnn which is for example not listen. In may case it is this version:

conda list | grep cudnn
```
pytorch                   2.1.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
```

Can you show me nvidia-smi on your GPU nodes? I wonder if old drivers could be the problem?

Locally, I'm running this:
```
 NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0 
```

**Comment by thorstenwagner** [comment]
This seems sounds interesting:
https://github.com/ultralytics/ultralytics/issues/4728

> The error message you are seeing, RuntimeError: CUDA error: device-side assert triggered, is typical when there may be an issue with the indices used in operations like scatter, gather, etc., most commonly indicating that an index is out of the given range.

However, as we run it on many machines and two clusters, I'm not sure what could be the issue on your side.

**Comment by thorstenwagner** [comment]
Last comment:

Could you maybe try if the following bugfix release of pytorch solves the issue?

https://github.com/pytorch/pytorch/releases/tag/v2.1.1

**Comment by rdrighetto** [comment]
Hi Thorsten,

Sorry for taking a while to get back to this, somehow I missed your latest messages here.
I just did a fresh install of tomotwin (again), hoping that this bugfix release of pytorch would do the trick, but it didn't. Same error.

At this point I am almost certain that the problem is our old NVIDIA driver. We are currently running this on our GPU nodes:
`NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7`
The latest cryoSPARC version also seems to [require](https://discuss.cryosparc.com/t/cuda-issue-after-updating-to-v-4-4/12584/9) version >=545 of the NVIDIA driver. I guess it's time for an update, but for this I'll need to contact our HPC team as I don't have sudo rights for this.

btw: what does the `-d 0` flag does in `tomotwin_embed.py` that makes it work?

I'll keep you posted. Thanks once again!

ps: also thanks for notifying us of the critical bugfix in the napari-tomotwin package, already installed!

**Comment by rdrighetto** [comment]
Hi Thorsten,

Our GPU nodes are gradually being updated to NVIDIA `Driver Version: 545.23.08`. I just tested on one of them and can confirm that it works fine. So, the solution is updating the NVIDIA driver.

Thanks for your help and have a nice weekend!

**Comment by thorstenwagner** [comment]
Thanks for the update. I will put it into our documentation
